addons:
  chrome: stable
language: python
python:
  - "3.7"
install:
  - python -m pip install --upgrade pip
  - pip install robotframework==3.1
  - pip install robotframework-excel==1.0.0b4
  - pip install robotframework-httplibrary==0.4.2
  - pip install robotframework-requests==0.6.6
  - pip install robotframework-seleniumlibrary==4.3.0
  - pip install robotframework-appiumlibrary==1.5.0.4
  - pip install webdrivermanager==0.7.4
  - pip install mysqlclient
  - pip install dbbot-sqlalchemy
  - webdrivermanager chrome
script: 
  robot -d OUTPUT --output XML/Output --Variable RunTypes:H RF_Framework
